### PR TITLE
Make trigger importable

### PR DESCRIPTION
**Pull request by 0xE282B0**
Hi @itowlson,
@leonardpahlke added the SQS trigger to the spin containerd shim as an example of how to add a trigger: https://github.com/deislabs/containerd-wasm-shims/pull/192. To import the `SqsTrigger` we had to create a `lib.rs` and move all the functionality except the main function there.

Is this something you can see in the scope of this crate?

### CODE REVIEW

**Review by itowlson — APPROVED** [review]

**Comment by itowlson** [comment]
@0xE282B0 Totally in scope.  I had been meaning to do this to the timer sample as well so that I could do a post on multiple trigger types in Lepton; we should establish this as the pattern for custom triggers going forward.  Thanks for tackling this!

**Comment by leonardpahlke** [comment]
Hey @itowlson, could we merge this PR & cut a new release so we can update the dependency in the containerd shim PR https://github.com/deislabs/containerd-wasm-shims/pull/192 🙌

**Comment by itowlson** [comment]
@leonardpahlke Sorry about that!  I'll get a release under way.

**Comment by itowlson** [comment]
@leonardpahlke Released v0.5.0 https://github.com/fermyon/spin-trigger-sqs/releases/tag/v0.5.0

**Comment by leonardpahlke** [comment]
Awesome! I will update the shim PR accordingly

**Pull request merged**
